# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Funk
email: johnsonzhong@hotmail.ca
description: > # this means to ignore newlines until "baseurl:"
  Fun drag and drop programming language for kids.
baseurl: "/Funk" # the subpath of your site, e.g. /blog
url: "http://johnsonzhong.me/" # the base hostname & protocol for your site
twitter_username: Lemon_byte
github_username:  Lemonpi

# Build settings
markdown: kramdown
